// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyr3d8oGSr5WoUrexdNw2eGzSiYPwDgpM',
    appId: '1:664214054992:web:b4184b241ff443623dc955',
    messagingSenderId: '664214054992',
    projectId: 'minimalchat-2e8f5',
    authDomain: 'minimalchat-2e8f5.firebaseapp.com',
    storageBucket: 'minimalchat-2e8f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfvLH6hnihF8un5IhUbJYGWcQjk4_eqCY',
    appId: '1:664214054992:android:14e986dbda5d688e3dc955',
    messagingSenderId: '664214054992',
    projectId: 'minimalchat-2e8f5',
    storageBucket: 'minimalchat-2e8f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDntsumq_zBJLIkUlBkKOtEqjsStosZygQ',
    appId: '1:664214054992:ios:0511319f8eadc9da3dc955',
    messagingSenderId: '664214054992',
    projectId: 'minimalchat-2e8f5',
    storageBucket: 'minimalchat-2e8f5.appspot.com',
    iosBundleId: 'com.example.minimalChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDntsumq_zBJLIkUlBkKOtEqjsStosZygQ',
    appId: '1:664214054992:ios:0511319f8eadc9da3dc955',
    messagingSenderId: '664214054992',
    projectId: 'minimalchat-2e8f5',
    storageBucket: 'minimalchat-2e8f5.appspot.com',
    iosBundleId: 'com.example.minimalChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyr3d8oGSr5WoUrexdNw2eGzSiYPwDgpM',
    appId: '1:664214054992:web:27ba43ba52790c193dc955',
    messagingSenderId: '664214054992',
    projectId: 'minimalchat-2e8f5',
    authDomain: 'minimalchat-2e8f5.firebaseapp.com',
    storageBucket: 'minimalchat-2e8f5.appspot.com',
  );
}
